const SET_CURRENT_USER = "SET_CURRENT_USER"
const CLEAR_CURRENT_USER = "CLEAR_CURRENT_USER"
const ADD_GOAL = "ADD_GOAL"
const EDIT_GOAL = "EDIT_GOAL"
const DELETE_GOAL = "DELETE_GOAL"

export {
  SET_CURRENT_USER,
  CLEAR_CURRENT_USER,
  ADD_GOAL, 
  EDIT_GOAL, 
  DELETE_GOAL 
}